version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: house_price_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: house_price_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: unless-stopped
